services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    networks:
      - default_network
  
  redis:
    container_name: redis_service
    image: "redis:latest"
    networks:
      - default_network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001-3005:3000
    links:
      - "mongodb:mongodb_database"
      - "redis:redis_database"
    environment:
      - MONGO_HOST=mongodb_database
      - MONGO_PORT=27017
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - PORT=3000
    networks:
      - default_network
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./tmp:/app/logs
  
networks:
  default_network:
    driver: bridge