# version: "3.9"

# services:
#   mongodb:
#     container_name: mongodb_service
#     image: "mongo:latest"
#     networks:
#       - mongo
  
#   redis:
#     container_name: redis_service
#     image: "redis:latest"
#     networks:
#       - redis
  
#   app:
#     container_name: hello-wops
#     build:
#       context: .
#     networks:
#       - mongo
#       - redis
#     ports: 
#       - "3000:3000"
#     environment:
#       - PORT=3000
#       - MONGO_HOST=mongodb_service
#       - MONGO_PORT=27017
#       - REDIS_HOST=redis_service
#       - REDIS_PORT=6379

# networks:
#   mongo:
#     driver: bridge
#   redis:
#     driver: bridge